### ISSUE TITLE
Downloading magnitude files

### ISSUE THREAD

**Issue by nayanar03** [ParikhKadam/bidaf-keras#11]
Hi,
The code is downloading magnitude files even if it is available locally, which is taking large amount of time. how to resolve this problem?

**Comment by ParikhKadam** [comment]
It doesn't download files if already downloaded. It's already verified..

**Comment by nayanar03** [comment]
@ParikhKadam Thank you for the response. You are right. It takes a long time only once. (but stil the magnitude files are already there). After the first implementation the problem is gone.
