### ISSUE TITLE
Run only in CPU version instead of GPU version.

### ISSUE THREAD

**Issue by hariteja97** [ParikhKadam/bidaf-keras#5]
The code that was written has GPU support but I want to run the code without GPU support i.e i need the code in CPU only. I tried to remove the multi-model-GPU package and its connections in the code but still I'M facing the issue 

Kindly help me to convert the code to CPU support only.

**Comment by ParikhKadam** [comment]
Install tensorflow==1.12.0 instead of tensorflow-gpu==1.12.0. That will solve the problem I think. Or you can just reinstall the package by using `pip install -U bidaf-keras[cpu]`.

Try any of these methods. If they don't work, please report here with the errors.. Thank you..

**Comment by hariteja97** [comment]
@ParikhKadam  Thanks for the comment . But when I try to run the code in windows its. showing these errors and I try to decode and change the syntax but of no use. I have attached the screenshot .

![error](https://user-images.githubusercontent.com/29245616/57780117-38266580-7745-11e9-9eb6-4e937d1d2ff8.png)


Can U help on how to rectify these error.

**Comment by hariteja97** [comment]
@ParikhKadam  Thanks a lot for the help and I have got a new doubt . I have tried this command  

python3 -m bidaf --model_name=bidaf_50.h5 --do_lowercase train --epochs=1 --steps_per_epoch=1 --validation_steps=1

 when I ran this  command I got the error
![Capture](https://user-images.githubusercontent.com/29245616/57801711-ef38d600-7771-11e9-8144-06366c98bf4c.PNG)


I dont understand what is this error Please help me it would be of great help

**Comment by ParikhKadam** [comment]
Have you downloaded our pretrained model "bidaf_50.h5" file? If yes, place the file in the path showed in this error which is "C:\\Python36\..." and the error will be solved..

**Comment by hariteja97** [comment]
Yes parikh I have tried once check the error I got when I did that .. once
check it sir .

Thanks a lot

**Comment by ParikhKadam** [comment]
The error clearly says that it cannot find the file "bidaf_50.h5" in that given path. Can you please show your files in that folder called saved_items?

**Comment by hariteja97** [comment]
@ParikhKadam/bidaf-keras
<reply@reply.github.com>  Thanks
a lot for ur help. I got the solution. I have a small issue here in my
ubuntu system. Its like , in my ubuntu all packages are not install and I
am not having any root access to connect to the ubuntu servers to download
them as they are blocked and cannot be accessed.

So when I run the same code it went in theano backened instead of
tensorflow. nd I was getting the error as  in tensor( it is considering it
as a list)  has not attribute type and it stops


I got the dev1.1json and train1.1 json file and model everything till
preprocessing is done . but training is not done.

Kindly help me in this issue

Thanks & Regards
Hari Teja.N

**Comment by ParikhKadam** [comment]
Great to hear that it solved.. BTW, the new issue you mentioned isn't clear to me. I understood that you cannot install packages on your linux machine and hence, Keras uses theano as backend which throws such error.

It should not happen.. Changing the backend in Keras shouldn't throw errors. That's what Keras is meant to do, right?

What isn't clear to me is, is this an error in our project or Keras? Can you please check it and tell?

I am closing this thread now. If you think that the error is in this project, kindly open a new issue specific to that error and I will surely help..

Thank you..
